language: node_js
node_js:
  - lts/*
addons:
  chrome: stable
  firefox: latest
services:
  - xvfb
before_script:
  - npm install nightwatch
  - npm install geckodriver --save-dev
  - npm install chromedriver --save-dev
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start
script:
  - npm test